config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  get '/happy', to: 'users#happy'
  get '/sad', to: 'users#sad'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/active.rb
class Active < ApplicationRecord
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :active
  
  after_create_commit { broadcast_prepend_to('users')}
  after_update_commit { broadcast_update_to('users') }
  after_update_commit { broadcast_prepend_to('users') }
  after_update_commit { broadcast_remove_to('users') }
  # broadcasts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index 
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to new_user_path
  end 

  def happy
    @users = User.all.where(happy: true)
  end

  def sad 
    @users = User.all.where(happy: false)
  end 

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path
  end

  private 

  def user_params
    params.require(:user).permit(:name, :happy)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboSort</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1> <%= link_to 'TurboSort', root_path %> </h1>
    <%= link_to 'happy ', happy_path %>
    <br>
    <%= link_to 'sad' , sad_path %>
    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<%# <% byebug %>
<%# users.each do |user| %> 
  <%# <li>= user.name - = user.happy ? 'happy' : 'sad'</li> %>
<%# end %> 

<div id=<%=dom_id user %> >
  <li> <%= user.name %> - <%= user.happy ? '😊' : '😔' %>  <%= link_to 'edit', edit_user_path(user) %></li>
</div>

app/views/users/edit.html.erb
<%= form_with model: @user do |u| %>
  <%= u.label :name %>
  <%= u.text_field :name %>
  
  <%= u.label :happy %>
  <%= u.check_box :happy %>
  <%= u.submit %>
<% end %>

app/views/users/happy.html.erb
<h1>Happy!</h1>
<%= turbo_stream_from 'users' %>
<ul id="users">
  <%# <%= render 'users', users: @users %>
  <%= render @users %>

</ul>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Turbo-Sort</title>
</head>
<body>
  <h1>Turbo Sort!</h1>
  <ul>
    <%= @users.each do |user| %>
      <li><%= user.name %> - <%= user.moode %>
    <% end %>
  </ul>
</body>
</html>

app/views/users/new.html.erb
<%= form_with model: @user do |u| %>
  <%= u.label :name %>
  <%= u.text_field :name %>
  
  <%= u.label :happy %>
  <%= u.check_box :happy %>
  <%= u.submit %>
<% end %>

app/views/users/sad.html.erb
<h1>sad</h1>
<%= turbo_stream_from 'users' %>
<ul id="users">
  <%# <%= render 'users', users: @users %>
  <%= render @users %>
</ul>